### PR TITLE
Emit local variable info for better debuggability

### LINKED ISSUE #9: propagate variable names into the emitted bytecode

### PR DESCRIPTION
**Pull request by athos**
This PR enables JiSE emitter to emit local variable info to the resulting bytecode to make it easier to debug it using a stock Java decompiler. Resolves #9.

This behavior is disabled by default (as with `javac`, which generates local variable info if the `-g` option is specified). A user can turn it on by setting a new system property `jise.debug` to `true`. So if you're using Clojure CLI, for example, you can launch a REPL with this debug option enabled with `clj -J-Djise.debug=true`.

Note that the property name (`jise.debug`) itself is subject to change before the final release.

### CODE REVIEW

**Comment by athos** [comment]
@xificurC Any thoughts?

**Comment by xificurC** [comment]
Thanks, I'll test this once merged. I was thinking if it might make sense to allow per-class or per-method emission via e.g. metadata (`^:debug`), but the global switch is probably enough

**Comment by athos** [comment]
Okay, then I'll merge it first 👍 

> I was thinking if it might make sense to allow per-class or per-method emission via e.g. metadata (^:debug)

Yeah, I thought there might be such a demand, but I wanted to keep things simple as a first step.

**Comment by xificurC** [comment]
I'm not sure why I wanted you to merge first. No harm done I guess.

I just tested it and the decompiled output shows the variable names and it helped the decompiler decide which local vars were supposed to be final. Thanks!

**Comment by athos** [comment]
No worries! I'm happy to hear that result 🤗

**Pull request merged**
